name: clean_architecture
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #clean architecture design packages  
  dartz: ^0.10.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  injectable: ^2.1.0
  retrofit: ^3.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  #general packages
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.1
  cached_network_image: ^3.2.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  #clean architecture design packages
  freezed: ^2.3.1  
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  injectable_generator: 
  build_runner: ^2.3.2 

flutter:
  uses-material-design: true

  fonts:
  - family: Mulish-Bold
    fonts:
      - asset: fonts/Mulish-Bold.ttf
  - family: Mulish-Light
    fonts:
      - asset: fonts/Mulish-Light.ttf
  - family: Mulish-Medium
    fonts:
      - asset: fonts/Mulish-Medium.ttf    
  - family: Mulish-Regular
    fonts:
      - asset: fonts/Mulish-Regular.ttf      
