name: amen_driver
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #clean architecture design packages  
  dartz: ^0.10.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  injectable: ^2.1.0
  retrofit: ^3.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  #general packages
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  fcm_config: ^3.3.7
  flutter_svg: ^1.1.1
  cached_network_image: ^3.2.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  bouncing_widget: ^2.0.0
  auto_animated: ^3.0.1
  delayed_display: ^2.0.0
  flutter_riverpod: ^1.0.4
  google_nav_bar: ^5.0.6
  motion_toast: ^2.2.1
  pin_code_fields: ^7.4.0
  bottom_picker: ^1.8.0
  intl: ^0.17.0
  responsive_framework: ^0.2.0
  photo_view: ^0.14.0
  custom_pop_up_menu: ^1.2.4
  just_bottom_sheet: ^1.3.0
  omni_datetime_picker: ^0.1.2
  awesome_loader_null_safety: ^0.0.2
  paginable: ^2.0.0
  shared_preferences: ^2.0.15
  file_picker: ^5.2.0+1
  paginated_list: ^1.0.3
  country_calling_code_picker: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #clean architecture design packages
  freezed: ^2.3.1  
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  injectable_generator: 
  build_runner: ^2.3.2 

flutter:
  uses-material-design: true
  assets:
    - icons/pngs/
    - icons/svgs/

  fonts:
  - family: Tajawal-Bold
    fonts:
      - asset: fonts/Tajawal-Bold.ttf
  - family: Tajawal-Light
    fonts:
      - asset: fonts/Tajawal-Light.ttf
  - family: Tajawal-Medium
    fonts:
      - asset: fonts/Tajawal-Medium.ttf    
  - family: Tajawal-Regular
    fonts:
      - asset: fonts/Tajawal-Regular.ttf 

  - family: Mulish-Bold
    fonts:
      - asset: fonts/Mulish-Bold.ttf
  - family: Mulish-Light
    fonts:
      - asset: fonts/Mulish-Light.ttf
  - family: Mulish-Medium
    fonts:
      - asset: fonts/Mulish-Medium.ttf    
  - family: Mulish-Regular
    fonts:
      - asset: fonts/Mulish-Regular.ttf      
